version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: blueocean
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./database/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  
  app:
    image: hacking-transitions-app
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:docker@database/blueocean
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pg-data:
  pgadmin-data:
